#!/bin/sh
if [ $# -eq 0 ]; then
	echo "Please provide your namespace, remember to escape backslash like so: \\\\\\\\\\\\\\"
	exit 1
fi

if [ -z $1 ]; then
	echo "Please provide a valid namespace, remember to escape backslash like so: \\\\\\\\\\\\\\"
	exit 1
fi

BUILD_DIR=build;
if [ $# -eq 2 ]; then
	BUILD_DIR=$2;
fi

echo ${BUILD_DIR}

if [ ! -d "${BUILD_DIR}" ]; then
	mkdir -p ${BUILD_DIR};
fi

echo "Building MySQL-Object-Model with namespace: $1"

for a in MOM*.php; do
	sed 's/Gyde\\MOM/'$1'/g' $a > ${BUILD_DIR}/$a
done
