#!/bin/sh
export MEMCACHE_HOST="127.0.0.1"
export MYSQL_HOST="localhost"
export MYSQL_USERNAME="mom"
export MYSQL_PASSWD="FaxChopShine"

cd /srv/mom/tests

./phpunit-8.4.phar --bootstrap autoload.php --configuration phpunit.xml --colors -v
